TensorFlow/squeezenet/setup.py

SqueezeNet's setup.py fails to find cifar2png in WSL: Linux uses `:` for to separate paths in $PATH; Windows uses `;`. Python abstracts this with `os.pathsep`.

Fix squeezenet setup.py path separator for WSL

---

TensorFlow/yolov3/detect.py

When saving output images to disk, the pixel values needs to be scaled from normalized values to [0,255] range.

Fix scaling of pixel values for detect.py

---

TensorFlow/squeezenet/src/save_squeezenet.py
TensorFlow/squeezenet/src/train_squeezenet.py

`TF_CPP_MIN_LOG_LEVEL = 3` can make it hard or impossible to know what's going on when an error happens. For example, it doesn't tell us if there was a problem while loading DirectML.dll.

Reduce min log level for SqueezeNet scripts

---

Libraries/DirectMLX.h

Compiling a graph with a single node is not the same as compiling the node itself _unless_ the input and output bindings are identical (same number and same order). See #68.

Remove single-node graph optimization

---

Libraries/DirectMLX.h

**Motivation**
A user faces null pointer issue while using the GRU operator. [Github Issue: 81](https://github.com/microsoft/DirectML/issues/81)
**Implementation**
In GRU operator to determine the 4th dimension of the output tensor, we were using 4th dimension of optional input _hiddenTensor_. So when this optional input is not provided, the program will throw null pointer exception.
As per the operator [description](https://docs.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_gru_operator_desc), we can also use 4th dimension of required input _recurrenceTensor_ to determine the 4th dimension of the output tensor. 
Hidden Tensor size: _{ 1, num_directions, batch_size, **hidden_size** }_
Recurrence Tensor size: _{ 1, num_directions, 3 * hidden_size, **hidden_size** }_

GRU Operator - Null pointer while determining the output tensor shape

---

Libraries/DirectMLX.h

Seeing code like this is confusing, because it *looks* as if we're passing dimensions of size 0 to an operator, when indeed those aren't tensor dimensions at all, but rather they're strides.
``` c++
complement = dml::Reinterpret(
complement,
{1, 1, num_elements, 2},
dml::TensorDesc::Dimensions({0, 0, 1, 0}) // Not actually dimensions of the tensor.
);
```
(note because the underlying typedef is the same, it shouldn't break anything anywhere that some existing caller passes `Dimensions`, but it enables clarity later)

Add typedef for strides which is less confusing than overloading dimensions

---

Libraries/DirectMLX.h

Fixes two warnings: unreferenced variable and implicit narrowing conversion.

Warning fixes in DMLX

---

Python/CMakeLists.txt

Patch fixes VS2019 build failures by defining the missing `ssize_t` POSIX type in the CMakefile.

Fix MSVC PyDML build.

---

.gitmodules
Python/CMakeLists.txt
Python/src/device.cpp
Python/src/device.h
Python/src/util.h

@wchao1115 @adtsai
This is the resource/residency management work that was developed with the help of the D3D12 team (based on 11on12 and D3D12 residency starter library), which was originally developed for Edge then forked to support more D3D12/DML-based projects which either lacked residency support and/or sub-allocation. This VidMM API is 1:1 with D3D12 so there is minimal to no integration overhead with DML. Users would configure the allocators to balance speed vs memory as they require.
PTAL, we are deploying it in a downstream DML project (WebNN) but it seems like there would be more beneifit adding it here. WDYT?

Enable fast DML resource allocation and residency management.

---

Libraries/DirectMLX.h

The original creation method will miss some optional inputs, and cause a mismatch between the input and the edge when creating the graph.

Modify the creation method of inputs to prevent missing optional inputs.

---

Libraries/DirectMLX.h

- Include wrl/client.h for cases where it's not already pulled in by e.g. windows.h
- Add support for unused/empty graph inputs, which can be useful for e.g. using a graph to emulate a larger operator.
- Add an explicit bool conversion for Expression, to allow for easy testing of empty expressions. (`if (expr) {}`)
- Allow a custom output datatype for QuantizeLinear, which is useful for selecting INT8 vs UINT8.
- Consistently use NULLs to represent empty, optional inputs for Conv, Gemm, and BatchNormTraining. In these cases the old code happened to work (because they only have a single optional input), but this change is to be consistent with #210 and help prevent further bugs.

Misc. improvements to DirectMLX.h

---

Python/src/device.cpp

I find that device.cpp uses `ThrowIfFailed `to handle errors, but I used `ReturnIfFailed `in my last [PR](https://github.com/microsoft/DirectML/pull/217). I am so sorry for that and now change it to align, please help to take a look! Thanks very much! @adtsai

Change ReturnIfFailed to ThrowIfFailed in Python\device.cpp

---

DxDispatch/src/dxdispatch/Device.cpp
DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/dxdispatch/main.cpp
DxDispatch/src/model/OnnxParsers.cpp
DxDispatch/src/model/OnnxParsers.h

The ONNX parsing logic and execution logic in dxdispatch are potentially using different D3D devices, which is setting a bad example.

Fix inconsistent ORT sessions in dxdispatch

---

DxDispatch/src/dxdispatch/OnnxDispatchable.cpp

when throwing an error for unbound tensor, the '%s' format is not
interpreted by fmt::format
Signed-off-by: Gabriel Ionescu <gabriel.ionescu@intel.com>

onnxdispatchable: fix error message formatting

---

Libraries/DirectMLX.h

Currently, argmin/argmax only output UINT32 for dml::Reduce(); however, this is based on an older version of DML and INT64 output types should now be supported as well.

Update Reduce in DirectMLX.h to take in output type for argmin/argmax

---

Samples/DirectMLSuperResolution/DirectMLSuperResolution.vcxproj
Samples/DirectMLSuperResolution/DirectMLXSuperResolution.vcxproj
Samples/DirectMLSuperResolution/Readme.md
Samples/DirectMLSuperResolution/packages.config
Samples/HelloDirectML/HelloDirectML.vcxproj
Samples/HelloDirectML/HelloDirectMLX.vcxproj
Samples/HelloDirectML/packages.config
Samples/HelloDirectML/readme.md
Samples/yolov4/Readme.md
Samples/yolov4/packages.config
Samples/yolov4/yolov4.cpp
Samples/yolov4/yolov4.vcxproj

- Update DirectML samples to use DML version 1.9.0
- Add metadata to readmes for sample browser automation
- Fix a couple of warnings when building yolov4 sample in VS2022

Update samples to use DML 1.9.0, and other small additions

---

Libraries/DirectMLX.h

One of the motivations behind this change is that DirectML doesn't support `ScaleBias` for 64 bit types, and therefore `dml::Identity` with a scale of `1.0f` doesn't work for `int64`.

Add DML_OPERATOR_ELEMENT_WISE_NEGATE API to DirectMLX.h

---

DxDispatch/cgmanifest.json
cgmanifest.json

This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …

Add `$schema` to `cgmanifest.json`

---

DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/Device.cpp
DxDispatch/src/dxdispatch/Device.h
DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/dxdispatch/main.cpp
DxDispatch/src/model/OnnxParsers.cpp
DxDispatch/src/model/OnnxParsers.h

Adds the option to override free dimensions by both name and denotation.

DxDispatch: ONNX free dim overrides by denotation

---

DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/dxdispatch/OnnxDispatchable.h
DxDispatch/src/model/OnnxParsers.cpp

Fixes an issue in the DxDispatch tool where generated output bindings use shape info from the session that is incorrect. See #276 
Some models have shape info that can't be known until after the model is executed, so there appears to be no way to reliably pre-allocate outputs with the IOBinding API. As a workaround, this change will let the execution provider allocate the output resources rather than providing D3D resources allocated by DxDispatch. This is acceptable because the generated output bindings aren't really used for anything anyway.

DxDispatch: fix ONNX models with dynamic output shapes

---

DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/model/OnnxParsers.cpp

This change enables running ONNX models with non-tensor-type outputs. These outputs cannot be allocated by the DML EP, so non-tensor outputs (and tensor outputs with unsupported data types) are allocated with the CPU allocator.

DxDispatch: support ONNX models with non-tensor outputs

---

DxDispatch/CMakeLists.txt
DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/DxModules.cpp
DxDispatch/src/dxdispatch/DxModules.h
DxDispatch/src/dxdispatch/ModuleInfo.cpp
DxDispatch/src/dxdispatch/ModuleInfo.h
DxDispatch/src/dxdispatch/main.cpp

This change adds a new command-line option, `--show_dependencies` (or `-S`), which will print run-time path/version info for the main DX/ORT dependencies (directml.dll, d3d12core.dll, etc.). This is useful when overlaying custom versions of dependencies that differ from what the tool was configured against.
- **Configured Version**: the version of the dependency that dxdispatch was configured/built against.
- **Loaded Path**: file path to the dependency loaded at run time
- **Loaded Version**: file version of the dependency loaded at run time
Example output:
```
PS S:\directml\DxDispatch\build\win-x64\Debug> .\dxdispatch.exe -S
DirectML:
- Configured Version : NuGet (Microsoft.AI.DirectML.1.9.1)
- Loaded Path        : S:\directml_github\DxDispatch\build\win-x64\Debug\directml.dll
- Loaded …
```

DxDispatch: option to show more info for loaded dependencies

---

DxDispatch/cmake/d3d12.cmake
DxDispatch/src/dxdispatch/Device.cpp
DxDispatch/src/dxdispatch/Device.h
DxDispatch/src/dxdispatch/Executor.cpp

The existing `Device::PrintDebugLayerMessages` method is a polling-based approach for printing D3D/DML debug messages. This PR switches to the newer callback-based approach, which means messages will be printed upon being added to the underlying D3D info queue.

DxDispatch: switch to debug message callback

---

DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/dxdispatch/OnnxDispatchable.h
DxDispatch/src/model/OnnxParsers.cpp

Three changes here:
- Fixes a bug where Ort::Env was not kept alive in the OnnxDispatchable class. The Ort::Session does not keep a ref on this object.
- OnnxParsers now allows inputs with data types not supported by DML. The OnnxDispatchable will explicitly allocate these inputs on the CPU.
- For inputs with data types that _are_ suppported by DML, but not explicitly bound, OnnxDispatchable will explicitly allocate the input as a DX resource. This path will only be taken if a JSON model is provided and some inputs are left unbound; OnnxParsers will always create bindings for supported inputs.
Some comments were added to help clarify all the binding paths that can be taken. Hopefully this is the last change I need to make here to support the more efficient IO binding with pre-allocated …

DxDispatch: keep ref on Ort::Env and allow CPU EP to allocate inputs

---

DxDispatch/cmake/onnxruntime.cmake
DxDispatch/cmake/pix.cmake
DxDispatch/src/model/OnnxParsers.cpp

Upgrades ORT to 1.13.1 and PIX event runtime to latest.
Only code change is replacing deprecated `OrtSession::GetInputName` with `OrtSession::GetInputNameAllocated`, which no longre requires the caller to free the returned string.

DxDispatch: Upgrade ORT & PIX

---

DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/model/OnnxParsers.cpp
DxDispatch/src/model/OnnxParsers.h

Final change (I hope) for ONNX-related binding. This will pre-allocate DX resources for outputs so long as their shapes are statically known. Dynamic shapes will be allocated by the EP (slightly less efficient). Minor code cleanup.

DxDispatch: pre-allocate ONNX outputs with static shapes

---

DxDispatch/models/hlsl_add_fp16.json
DxDispatch/models/hlsl_add_fp32.json
DxDispatch/models/onnx_gemm.json

Running DxDispatch from another directory (like the build\win-x64\Debug folder) yields errors. This just makes it more intuitive.
```
Failed to execute the model: ERROR while initializing 'add':
S:\DirectML@github\DxDispatch\src\dxdispatch\HlslDispatchable.cpp(194)\dxdispatch.exe!00007FF6CB381025: (caller: 00007FF6CB3577E9) Exception(1) tid(4778)
80070003 The system cannot find the path specified.
```

Make model files relative

---

PyTorch/1.13/yolov3/.gitignore
PyTorch/1.13/yolov3/data/coco128.yaml
PyTorch/1.13/yolov3/data/hyp.scratch.yaml
PyTorch/1.8/yolov3/.gitignore
PyTorch/1.8/yolov3/data/coco128.yaml
PyTorch/1.8/yolov3/data/hyp.scratch.yaml

Add coco.yaml and hyperparam.yaml to allow yolov3 scripts to run. Note that this doesn't actually add any dataset, just points the scripts to the correct download location. 
Repro steps: Do a clean clone of DirectML repo and run train.py. Since the data folder doesn't exist (including the yaml metadata files), training can't run.

add training/hyperparam yaml files- not the actual data

---

DxDispatch/tools/AnalyzePixGpuCapture.ps1

`$CurrenntEvent.Parent` is treated as a string, so this line is doing a string comparison instead of a numeric comparison.

Comparison type fix in dxdispatch helper script

---

README.md

The link is stale (before the plugin repo was created) which makes it confusing for users.

Repoint Readme.md issue link to current TensorFlow plugin repo

---

Libraries/DirectMLX.h

Adds some helpers to DirectMLX.h for setting graph node names. This will be useful in future versions of DML that incorporate node names into PIX events. This feature is intended to be helpful in correlating network architecture blocks with individual operators, so naming is done on the graph builder with a push-pop model (names separated by underscores).
Example:
```cpp
dml::Graph g(dmlDevice.Get());
auto a = dml::InputTensor(g, 0, dml::TensorDesc{ DML_TENSOR_DATA_TYPE_FLOAT32, dml::TensorDimensions{5} });
auto b = dml::InputTensor(g, 0, dml::TensorDesc{ DML_TENSOR_DATA_TYPE_FLOAT32, dml::TensorDimensions{5} });
g.PushName("arithmetic");
auto c = a + b * b * 5;
g.PopName();
```
You can also use a name scope object to automatically pop the name within a scope. Example:
```cpp …
```

Support for node names in DMLX graphs

---

DxDispatch/CMakeLists.txt
DxDispatch/README.md
DxDispatch/cgmanifest.json
DxDispatch/cmake/d3d12.cmake
DxDispatch/cmake/dxcompiler.cmake
DxDispatch/cmake/onnxruntime.cmake
DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/model/OnnxParsers.cpp
DxDispatch/tools/AnalyzePixGpuCapture.ps1

- Updates binary dependencies (dxc, d3d, ort)
- Changes the default event duration measurement in AnalyzePixGpuCapture.ps1 from TOP-to-EOP to EOP-to-EOP.
- Fix ORT C++ API breaking changes in 1.14 (`Ort::Unowned<Ort::TensorTypeAndShapeInfo>` return type replaced with something else)

Update DxDispatch dependencies and event duration method

---

component-governance.yml

Increase component governance task timeout from 6 min (default) to 20 min to avoid blocking PRs.

Increase CG task timeout

---

docs/CompVis_Stable_Diffusion_Instructions.md

`accelerate` is recommended by the script when converting stable diffusion since it can reduce memory usage.

Add `accelerate` to the package requirements

---

.gitmodules
Python/CMakeLists.txt

Fix the "error C2027: use of undefined type '_frame'" by update to pybind11 v2.10.
Use CMAKE_CXX_STANDARD to fix CMake error "PYBIND11_CPP_STANDARD should be replaced with CMAKE_CXX_STANDARD" after update pybind11.

Update to newer version of pybind11 to fix compile error

---

DxDispatch/CMakeLists.txt
DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/Device.cpp
DxDispatch/src/dxdispatch/Device.h
DxDispatch/src/dxdispatch/main.cpp

This option is useful for checking cold cache initialization time. Developer mode is required.

Dxdispatch: option to clear D3D shader caches

---

DxDispatch/CMakeLists.txt
DxDispatch/ThirdPartyNotices.txt
DxDispatch/cgmanifest.json
DxDispatch/cmake/onnxruntime_extensions.cmake
DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/DxModules.cpp
DxDispatch/src/dxdispatch/DxModules.h
DxDispatch/src/dxdispatch/ModuleInfo.cpp
DxDispatch/src/dxdispatch/ModuleInfo.h
DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/dxdispatch/OnnxDispatchable.h
DxDispatch/src/dxdispatch/config.h.in

Adds support for running ONNX models with a dependency on ortextensions.dll. This library is not enabled by default, so you must supply `--enable_ort_extensions` when running the model.

Support ORT extensions in DxDispatch

---

Libraries/DirectMLX.h

Updating `dml Expression DequantizeLinear` to dequantize depending on Scale(which is same as output) data type, instead of `DML_TENSOR_DATA_TYPE_FLOAT32` as default.

Dequantize by scale data type

---

index.html

Corrected capitalization of GitHub (the site had it as Github originally)

corrected capitalization of GitHub on DML page

---

DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/OnnxDispatchable.cpp

This is the profiling option that generates a .json trace that can be viewed in chromium browser. It doesn't contain useful perf information for DirectML since it captures only the CPU timeline, but it makes it easy to see the partitioning at a glance and which ops are falling back to the CPU, if any.

Add profiling option to DxDispatch

---

Libraries/DirectMLX.h

Update dml::Resample to include the `Antialiased` attribute, which calls the new `DML_OPERATOR_RESAMPLE3` to return an antialiased version of the input.

update dml::Resample to include RESAMPLE3 api

---

DxDispatch/CMakeLists.txt
DxDispatch/README.md
DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/Device.cpp
DxDispatch/src/dxdispatch/Device.h
DxDispatch/src/dxdispatch/Dispatchable.h
DxDispatch/src/dxdispatch/DmlDispatchable.cpp
DxDispatch/src/dxdispatch/DmlDispatchable.h
DxDispatch/src/dxdispatch/Executor.cpp
DxDispatch/src/dxdispatch/HlslDispatchable.cpp
DxDispatch/src/dxdispatch/HlslDispatchable.h
DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/dxdispatch/OnnxDispatchable.h
DxDispatch/src/dxdispatch/dxDispatchWrapper.cpp

This change adds a few features/fixes for profiling (mainly ONNX models). This merges a few private commits from @jeffbloo (thanks Jeff!).
- Option to change size of the GPU timestamp buffer (or disable GPU timing entirely)
- Option to set stable power state & disable background processing in the UMD
- TDR is disabled in the command queue
- Fix a slow memory leak in the DxDispatch command allocator (only applies to ONNX models when GPU timestamps are used; the command allocator wasn't being reset)

DxDispatch profiling improvements

---

Libraries/DirectMLX.h

When DML_TARGET_VERSION is less than 0x6200.

[DirectMLX] Fixed the local variable initialized but not referenced issue.

---

DxDispatch/CMakeLists.txt
DxDispatch/cgmanifest.json
DxDispatch/cmake/directml.cmake
Libraries/DirectMLX.h
Releases.md
Samples/DirectMLSuperResolution/DirectMLSuperResolution.vcxproj
Samples/DirectMLSuperResolution/DirectMLXSuperResolution.vcxproj
Samples/DirectMLSuperResolution/Kits/DirectXTK12/DirectXTK_Desktop_2017_Win10.vcxproj
Samples/DirectMLSuperResolution/packages.config
Samples/HelloDirectML/HelloDirectML.vcxproj
Samples/HelloDirectML/HelloDirectMLX.vcxproj
Samples/HelloDirectML/main.cpp
Samples/HelloDirectML/packages.config
Samples/yolov4/Kits/DirectXTK12/DirectXTK_Desktop_2017_Win10.vcxproj
Samples/yolov4/packages.config
Samples/yolov4/yolov4.vcxproj

- Release notes for the DML 1.13.0.
- Updates our C++ samples and DxDispatch to use the latest DML 1.13.0 redistributable package.
- Fix a few warnings in DirectMLX.h (treated as errors in C++ samples).
- Update samples to a newer MSVC toolset (VS2022).

Update samples and release notes for DML 1.13

---

DxDispatch/CMakeLists.txt
DxDispatch/cgmanifest.json
DxDispatch/cmake/d3d12.cmake
DxDispatch/doc/Guide.md
DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/Device.cpp
DxDispatch/src/dxdispatch/Device.h
DxDispatch/src/dxdispatch/DxModules.cpp
DxDispatch/src/dxdispatch/DxModules.h
DxDispatch/src/dxdispatch/dxDispatchWrapper.cpp

1. When code was refactored the old mechanism for setting agility SDK did not work, updated code to do it programmatically 
2. Updated code to better debug TDRs with Dred - can analyze through debugger extension using d3d12!D3D12DeviceRemovedExtendedData (https://learn.microsoft.com/en-us/windows/win32/direct3d12/use-dred)
3. Update Agility SDK for DX12 to latest supported version

Update Code to work with agility SDK, added Dred, update agilitySdk

---

Libraries/DirectMLX.h
Samples/HelloDirectML/main.cpp

DML feature level 6.2 supports a new node type, DML_GRAPH_NODE_TYPE_CONSTANT, which allows applications to supply constant data through a void* instead of a graph input (D3D resource). Unlike D3D resources, constant data is available during graph compilation.
This change extends the DirectMLX.h helper to support constant nodes. For efficiency, DMLX does not make a copy of the application's data; the application needs to keep the backing memory alive until graph compilation completes.

Support constant data nodes in DirectMLX

---

DxDispatch/CMakeLists.txt
DxDispatch/src/dxdispatch/Adapter.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/Device.cpp
DxDispatch/src/dxdispatch/Device.h
DxDispatch/src/dxdispatch/DmlDispatchable.cpp
DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/dxdispatch/dxDispatchWrapper.cpp

This change avoids extra copies (uploadHeap->defaultHeap, defaultHeap->readbackHeap) by using custom heaps for adapters with cache-coherent UMA.

Use custom heaps by default for cache-coherent UMA devices

---

DxDispatch/CMakeLists.txt
DxDispatch/src/dxdispatch/Device.cpp

The debug is supposed to be log info/warning/error messages, but it's been a no-op since refactoring to use a logger. Presumably the context* was supposed to be the logger instance, but this was never passed in.

Fix debug callback not showing output

---

DxDispatch/CMakeLists.txt
DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/Device.cpp
DxDispatch/src/dxdispatch/Device.h
DxDispatch/src/dxdispatch/Executor.cpp
NOTICE

Optional argument "--present_separator" which injects a present between each inference iteration. This is helpful for external tools which require a notion of frames to digest the captured data.
The functionality is only compiled into the binary if DX_PRESENT_SEPARATOR is defined.

Dxdispatch present separator

---

DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/PixCaptureHelper.cpp
DxDispatch/src/dxdispatch/PixCaptureHelper.h

Recent WinPix releases have added support for programmatic timing captures.  This change enables that functionality via the "-c timing" argument to DxDispatch.

Add DxDispatch PIX timing capture command line support on windows

---

DxDispatch/doc/Guide.md
DxDispatch/models/_schema.json
DxDispatch/src/dxdispatch/Executor.cpp
DxDispatch/src/model/JsonParsers.cpp
DxDispatch/src/model/Model.h

To verify some small differences between GPU's (for WebNN failure diagnostic):
```json
"commands": 
[
{
"type": "dispatch",
"dispatchable": "batchNormalization",
"bindings": 
{
"InputTensor": "input",
"MeanTensor": "mean",
"VarianceTensor": "variance",
"ScaleTensor": "scale",
"BiasTensor": "bias",
"OutputTensor": "output"
}
},
{ "type": "print", "resource": "output"},
{ "type": "print", "resource": "output", "verbose": false},
{ "type": "print", "resource": "output", "verbose": true} // <-----
]
```

DxDispatch add print verbose option including exact bit patterns via hex

---

DxDispatch/src/dxdispatch/Executor.cpp

Sigh, third time is a charm 🤦‍♂️😔.
- Print hex as hex, addressing @BruceDai's comment: https://github.com/microsoft/DirectML/pull/706#pullrequestreview-2937898952

DxDispatch print verbose hex as hex
