HelloDirectML/HelloDirectML.vcxproj
HelloDirectML/main.cpp

- correcting target to released SDK 18362
- filtering by DX12 device with feature level 11.0 instead of 12.0

- correcting target to released SDK 18362 and feature level 11.0 instead of 12.0

---

TensorFlow/README.md

Small tweaks to match the main repo README

TensorFlow README updates

---

Releases.md

Adds a placeholder for DirectML release notes.

Create release notes placeholder file

---

Releases.md

This will need to be updated with some link when docs are on MSDN.

Fill in some release notes

---

Releases.md

With the docs now on MSDN, this page can act as a quick reference and redirect to the full notes.

Abridged release notes

---

Libraries/DirectMLX.h

Fix clang build issues of DirectMLX.h (#77)

---

Samples/HelloDirectML/main.cpp

See https://github.com/microsoft/DirectML/issues/85

Add missing call to reset D3D command allocator

---

Libraries/DirectMLX.h

Pastes the DMLX from the TF repo here. 
There are some changes aside from my own, but I assume it's good to bring those over too and make it match.

bring DirectMLX.h changes over from tf repo

---

Libraries/DirectMLX.h

At the moment, since Add1 supports fewer types than Add, it's impossible to run int32 or uint32 Add with DirectMLX.

Add an unfused version of Add

---

Libraries/DirectMLX.h

required for tensorflow batchtospace/spacetobatch [(PR)](https://github.com/microsoft/tensorflow-directml/pull/308)

depthtospace/spacetodepth DMLX

---

Libraries/DirectMLX.h

This wraps two DirectML APIs in DirectMLX:
* DML_OPERATOR_BATCH_NORMALIZATION_TRAINING 
* DML_OPERATOR_BATCH_NORMALIZATION_TRAINING_GRAD

DirectMLX support for BatchNorm training APIs

---

README.md

Remove "Preview" from TensorFlow-DirectML section

Remove "Preview" from TensorFlow-DirectML section

---

PyTorch/.gitignore
PyTorch/README.md
PyTorch/classification/dataloader_classification.py
PyTorch/classification/test_classification.py
PyTorch/classification/train_classification.py
PyTorch/data/cifar.py
PyTorch/data/imagenet_classes.txt
PyTorch/requirements.txt
PyTorch/resnet50/README.md
PyTorch/resnet50/predict.py
PyTorch/resnet50/requirements.txt
PyTorch/resnet50/test.py
PyTorch/resnet50/train.py
PyTorch/squeezenet/README.md
PyTorch/squeezenet/predict.py
PyTorch/squeezenet/requirements.txt
PyTorch/squeezenet/test.py
PyTorch/squeezenet/train.py
README.md

Introducing PyTorch+DirectML Samples
This PR includes the associated sample scripts to run PyTorch on DirectML.

Introducing PyTorch+DirectML Samples

---

Libraries/DirectMLX.h

Add ability to explicitly specify output sizes for Average/MaxPooling

---

DxDispatch/models/dml_gemm.json

Adds example of using DML GEMM operator:
```
[1]  * [4,5,6]  + [2,2,2] = [6,7,8]
[2]               [2,2,2]   [10,12,14]
[3]               [2,2,2]   [14,17,20]
```

GEMM example

---

TensorFlow/TF2/squeezenet/squeezenet.py

Increased default batch size so model trains faster, set Adam optimizer hyperparameters to train better (default hyperparameters caused the model to not learn at all with Adam)

Update TF2 Squeezenet model hyperparameters

---

DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/Executor.cpp

- add duration mode (-t timeInMs instead of -i iterations)
- also report median time

Minor Enhancements to dx-dispatch

---

Libraries/DirectMLX.h

Hi,
I tried to copy the patterns used by similar functions as much as I could. They are working for my current use case, I wouldn't say it's been heavily tested yet though. I figured it might save the next person some trouble to contribute them back to the library.
Thanks!

Add ConvolutionInteger & QuantizedLinearConvolution to DirectMLX.h

---

DxDispatch/cgmanifest.json
DxDispatch/cmake/directml.cmake
Python/README.md
Python/setup.py
Releases.md
Samples/DirectMLSuperResolution/DirectMLSuperResolution.vcxproj
Samples/DirectMLSuperResolution/DirectMLXSuperResolution.vcxproj
Samples/DirectMLSuperResolution/packages.config
Samples/HelloDirectML/HelloDirectML.vcxproj
Samples/HelloDirectML/HelloDirectMLX.vcxproj
Samples/HelloDirectML/packages.config
Samples/yolov4/packages.config
Samples/yolov4/yolov4.vcxproj

- Added release note for DML 1.9.1
- Update version of DML to 1.9.1 in all samples and verified that they are running successfully.

Update DML version for samples and release notes

---

DxDispatch/CMakeLists.txt
DxDispatch/src/dxdispatch/Adapter.cpp
DxDispatch/src/dxdispatch/DxModules.h

Fixes some build build regressions related to dynamic loading of modules on PC (would be nice to eventually add this flavor to our CI pipeline).

Minor fixes for Xbox build for DXD

---

DxDispatch/cmake/directml.cmake
Samples/DirectMLSuperResolution/DirectMLSuperResolution.vcxproj
Samples/DirectMLSuperResolution/DirectMLXSuperResolution.vcxproj
Samples/DirectMLSuperResolution/packages.config
Samples/HelloDirectML/HelloDirectML.vcxproj
Samples/HelloDirectML/HelloDirectMLX.vcxproj
Samples/HelloDirectML/packages.config
Samples/yolov4/packages.config
Samples/yolov4/yolov4.vcxproj

Updated all 3 DirectML samples and DxDispatch tool to point to [DirectML1.10.0](https://www.nuget.org/packages/Microsoft.AI.DirectML/1.10.0)

Update samples and dxdispatch to DML1.10

---

DxDispatch/cmake/directml.cmake
Releases.md
Samples/DirectMLSuperResolution/DirectMLSuperResolution.vcxproj
Samples/DirectMLSuperResolution/DirectMLXSuperResolution.vcxproj
Samples/DirectMLSuperResolution/packages.config
Samples/HelloDirectML/HelloDirectML.vcxproj
Samples/HelloDirectML/HelloDirectMLX.vcxproj
Samples/HelloDirectML/packages.config
Samples/yolov4/packages.config
Samples/yolov4/yolov4.vcxproj

- Updated all 3 DirectML samples and DxDispatch tool to point to [DirectML1.10.1](https://www.nuget.org/packages/Microsoft.AI.DirectML/1.10.1)
- Updated Releases.md

Update samples and dxdispatch to DML1.10.1

---

DxDispatch/src/dxdispatch/Executor.cpp

When I do performance profiling, I pay attention to the gpu/cpu timing of each iteration, especially for the timing of  the first dispatch. So I want to enable printing them under -v flag in this PR. Notice that I disable skipping the first time warming up, but only keep align with the actual situation. If you think this feature should be under -v flag, I can move it under another new flag, for example, -p (performance_profiling) flag. Thanks!

DxDispatch: Print GPU/CPU timing of each iteration under -v flag

---

Releases.md
Samples/DirectMLSuperResolution/DirectMLSuperResolution.vcxproj
Samples/DirectMLSuperResolution/DirectMLXSuperResolution.vcxproj
Samples/DirectMLSuperResolution/packages.config
Samples/HelloDirectML/HelloDirectML.vcxproj
Samples/HelloDirectML/HelloDirectMLX.vcxproj
Samples/HelloDirectML/packages.config
Samples/yolov4/packages.config
Samples/yolov4/yolov4.vcxproj

- Updated all DML samples with DML1.11.0
- Updated Release notes.

Update DML samples and release notes for DML1.11.0

---

community.html

Added quotation marks around the quotes on the community page.

Adding quotation marks to quotes

---

Libraries/DirectMLX.h

complementary of https://github.com/microsoft/DirectML/pull/495

guard additional parameter of resample2

---

Libraries/DirectMLX.h

Fix Resample build. Related: https://github.com/microsoft/DirectML/pull/517

[DirectMLX] fix build issue in Resample when TARGET_VERSION < 0x6200

---

Libraries/DirectMLX.h

Only use resample3 if feature level 6.3 enabled

[directmlx] Move resample3 to feature level 6.3

---

README.md

Fix links for TF and PT with DirectML

---

DxDispatch/CMakeLists.txt
DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/Device.cpp
DxDispatch/src/dxdispatch/Device.h
DxDispatch/src/dxdispatch/DmlDispatchable.cpp
DxDispatch/src/dxdispatch/Executor.cpp
DxDispatch/src/dxdispatch/HlslDispatchable.cpp
DxDispatch/src/dxdispatch/OnnxDispatchable.cpp
DxDispatch/src/dxdispatch/PixCaptureHelper.cpp
DxDispatch/src/dxdispatch/dxDispatchWrapper.cpp
DxDispatch/src/model/JsonParsers.cpp

1. Update compile flags with /W3
2. Update link flags with /CETCOMPAT
3. Update range checks to meet /W3

Update compile and link commands to address binskim

---

Libraries/DirectMLX.h

Fixing a bug from refactoring related to CR comments. :)

Fix bug in graph constant nodes

---

README.md

https://github.com/microsoft/DirectML/blob/master/README.md 
#PingMSFTDocs

Typo "Pytorch"→"PyTorch"

---

DxDispatch/CMakeLists.txt
DxDispatch/src/dxdispatch/CommandLineArgs.cpp
DxDispatch/src/dxdispatch/CommandLineArgs.h
DxDispatch/src/dxdispatch/Device.cpp
DxDispatch/src/dxdispatch/Device.h
DxDispatch/src/dxdispatch/Executor.cpp
DxDispatch/src/dxdispatch/dxDispatchWrapper.cpp
DxDispatch/src/dxdispatch/pch.h

DXGI isn't supported on WSL, and not all D3D feature levels support DXGI.

Minor fixes for formatting and present seperator

---

Samples/DirectMLNpuInference/main.cpp

Also renamed variables/modified codeflow to improve readability.

Add code for creating Generic ML devices to NPU starter sample

---

Releases.md
Samples/DirectMLNpuInference/DirectMLNpuInference.vcxproj
Samples/DirectMLNpuInference/packages.config
Samples/DirectMLSuperResolution/DirectMLSuperResolution.vcxproj
Samples/DirectMLSuperResolution/DirectMLXSuperResolution.vcxproj
Samples/DirectMLSuperResolution/packages.config
Samples/HelloDirectML/HelloDirectML.vcxproj
Samples/HelloDirectML/HelloDirectMLX.vcxproj
Samples/HelloDirectML/packages.config
Samples/yolov4/packages.config
Samples/yolov4/yolov4.vcxproj

Post release DML1.15.1, this change updates the samples and add release notes.

Update Release Notes and Samples for DML1.15.1

---

Samples/DirectML_ESRGAN/helpers.cpp

Workaround for certain iGPUs that aren't behaving correctly with a compute queue.

Update ESRGAN sample to use direct queue for GPUs

---

Samples/DirectML_ESRGAN/README.md

Justin Stoecker updated ESRGAN for NPU, we need to update readme for Qualcomm.

Per Ashrit Shetty: Update readme for error message

---

Samples/DirectML_ESRGAN/README.md

Update the readme of the DirectML_ESRGAM sample to include the blog post link for further technical requirements.

Update ESRGAN Sample Readme
